# 4.6 GPU计算

In [16]:
!nvidia-smi # 对Linux/macOS用户有效

'nvidia-smi' �����ڲ����ⲿ���Ҳ���ǿ����еij���
���������ļ���


In [17]:
import torch
from torch import nn

print(torch.__version__)

1.13.1+cpu


## 4.6.1 计算设备

In [18]:
torch.cuda.is_available() # cuda是否可用

False

In [19]:
torch.cuda.device_count() # gpu数量

0

In [20]:
torch.cuda.current_device() # 当前设备索引, 从0开始

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
torch.cuda.get_device_name(0) # 返回gpu名字

'GeForce GTX 1050'

## 4.6.2 `Tensor`的GPU计算

In [ ]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [ ]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [ ]:
x.device

device(type='cuda', index=0)

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
# or
x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [ ]:
y = x**2
y

tensor([1, 4, 9], device='cuda:0')

In [ ]:
# z = y + x.cpu()

## 4.6.3 模型的GPU计算

In [ ]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [ ]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [ ]:
x = torch.rand(2,3).cuda()
net(x)

tensor([[-0.5574],
        [-0.3792]], device='cuda:0', grad_fn=<ThAddmmBackward>)